// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc_BVyUp5HhTV9dXzatqJi0sFAf4HC0fQ',
    appId: '1:1065463394539:web:ba67a6a5b06754e7d0ceae',
    messagingSenderId: '1065463394539',
    projectId: 'faspace-80905',
    authDomain: 'faspace-80905.firebaseapp.com',
    storageBucket: 'faspace-80905.firebasestorage.app',
    measurementId: 'G-1X9F1YWT3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT_RUaZU3F7oBtWem-atUD6tni35Nx9hw',
    appId: '1:1065463394539:android:9fded1fb715f9911d0ceae',
    messagingSenderId: '1065463394539',
    projectId: 'faspace-80905',
    storageBucket: 'faspace-80905.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl1DZYpxFzkKj_F7lv7HSzKcoCPIYCP54',
    appId: '1:1065463394539:ios:1aed2af4d9168aa9d0ceae',
    messagingSenderId: '1065463394539',
    projectId: 'faspace-80905',
    storageBucket: 'faspace-80905.firebasestorage.app',
    iosBundleId: 'com.farid.faspace.faSpace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl1DZYpxFzkKj_F7lv7HSzKcoCPIYCP54',
    appId: '1:1065463394539:ios:1aed2af4d9168aa9d0ceae',
    messagingSenderId: '1065463394539',
    projectId: 'faspace-80905',
    storageBucket: 'faspace-80905.firebasestorage.app',
    iosBundleId: 'com.farid.faspace.faSpace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc_BVyUp5HhTV9dXzatqJi0sFAf4HC0fQ',
    appId: '1:1065463394539:web:4a7d1bf20dac8e18d0ceae',
    messagingSenderId: '1065463394539',
    projectId: 'faspace-80905',
    authDomain: 'faspace-80905.firebaseapp.com',
    storageBucket: 'faspace-80905.firebasestorage.app',
    measurementId: 'G-663DPLVR0F',
  );
}
